### PR TITLE
Looks for existing Dockerfile and fails if found

### LINKED ISSUE #67: Fail build if a dockerfile is found in src/main/docker/Dockerfile
Remove any ambiguity - this dockerfile will be completely ignored.

### PR DESCRIPTION
**Pull request by ChengyuanZhao**
Fixed #67

### CODE REVIEW

File: java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/ConfigFileFinder.java [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+
+import com.google.common.annotations.VisibleForTesting;
+import com.google.common.base.Preconditions;
+
+import java.nio.file.Files;
+import java.nio.file.Path;
+import java.util.List;
+import java.util.Optional;
+
+public abstract class ConfigFileFinder {
```
Comment (aslo) [inline java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/ConfigFileFinder.java]: I think that this ConfigFileFinder class hierarchy may be adding more complexity than is necessary. 

We are already checking for the presence of a Dockerfile at the root (and failing if it's found) in the [`BuildContext` class](https://github.com/GoogleCloudPlatform/runtime-builder-java/blob/master/java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java#L148) . IMO the check for the file at `src/main/docker/Dockerfile` should happen alongside that.

Comment (ChengyuanZhao) [reply java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/ConfigFileFinder.java]: Yea I agree, I'll move it there.

File: java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java [hunk 2]
```diff
@@ -145,7 +145,8 @@ private void writeDockerFile() throws IOException {
     Path dockerFilePath = workspaceDir.resolve(DOCKERFILE_NAME);
 
     // fail loudly if a Dockerfile already exists
-    if (Files.exists(dockerFilePath)) {
+    if (Files.exists(dockerFilePath)
+        || Files.exists(workspaceDir.resolve("src/main/docker/" + DOCKERFILE_NAME))) {
```
Comment (meltsufin) [inline java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java]: Extract `src/main/docker` to constant like `SRC_DOCKER_DIR`.

File: java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java [hunk 3]
```diff
@@ -145,7 +145,8 @@ private void writeDockerFile() throws IOException {
...
       throw new IllegalStateException("Custom Dockerfiles are not supported. If you wish to use a "
           + "custom Dockerfile, consider using runtime: custom. Otherwise, remove the Dockerfile "
           + "from the root of your sources to continue.");
```
Comment (meltsufin) [inline java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java]: This message is not longer accurate because we might be finding a `Dockerfile` in `src/main/docker`.

File: java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java [hunk 4]
```diff
@@ -145,13 +146,17 @@ private void writeDockerFile() throws IOException {
     Path dockerFilePath = workspaceDir.resolve(DOCKERFILE_NAME);
 
     // fail loudly if a Dockerfile already exists
-    if (Files.exists(dockerFilePath)
-        || Files.exists(workspaceDir.resolve("src/main/docker/" + DOCKERFILE_NAME))) {
+    if (Files.exists(dockerFilePath)) {
```
Comment (meltsufin) [inline java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java]: I'm thinking we can just have an immutable list of Dockerfile locations and loop through it here. The exception message can simply substitute the location in which it found the unexpected Dockerfile. WDYT?

Comment (ChengyuanZhao) [reply java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java]: Yup. However, should the case of just the file name be special (that one telling the user he can use 
"custom" option), while the other cases inside various directories just tell the user to remove the file?

File: java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java [hunk 5]
```diff
@@ -49,7 +51,8 @@
 public class BuildContext {
 
   private static final String DOCKERFILE_NAME = "Dockerfile";
-  private static final String EXISITING_DOCKER_DIR = "src/main/docker/";
+  private static final List<String> EXISITING_DOCKER_DIRS =
+      ImmutableList.of("src/main/docker/");
```
Comment (meltsufin) [inline java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java]: `ImmutableList.of("", "src/main/docker/")` to do both in one go

File: java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java [hunk 6]
```diff
@@ -152,9 +155,11 @@ private void writeDockerFile() throws IOException {
           + "from the root of your sources to continue.");
     }
 
-    if (Files.exists(workspaceDir.resolve(EXISITING_DOCKER_DIR + DOCKERFILE_NAME))) {
-      throw new IllegalStateException("There is an unexpected Dockerfile in " + EXISITING_DOCKER_DIR
-      + ". Please remove it to continue.");
+    for (String dir : EXISITING_DOCKER_DIRS) {
```
Comment (meltsufin) [inline java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java]: Can we merge this with the block above? The message can be what we have above, slightly modified to point to the path.

File: java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java [hunk 7]
```diff
@@ -146,22 +146,17 @@ public void writeDockerResources() throws IOException {
...
-          + "from the root of your sources to continue.");
-    }
-
     for (String dir : EXISITING_DOCKER_DIRS) {
       if (Files.exists(workspaceDir.resolve(dir + DOCKERFILE_NAME))) {
-        throw new IllegalStateException("There is an unexpected Dockerfile in " + dir
-            + ". Please remove it to continue.");
+        throw new IllegalStateException("Custom Dockerfiles aren't supported. If you wish to use a "
+            + "custom Dockerfile, consider using runtime: custom. Otherwise, remove the Dockerfile "
+            + "from " + dir + " to continue.");
```
Comment (meltsufin) [inline java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java]: In the case of the root dir, this will just say `from to continue`.
maybe something like: `"from the " + (dir == "" ? "root" : dir) + " directory of your sources to continue"`.

File: java-runtime-builder-app/src/test/java/com/google/cloud/runtimes/builder/config/domain/BuildContextTest.java [hunk 8]
```diff
@@ -97,6 +97,16 @@ public void testWriteDockerFilesWithExistingDockerfile() throws IOException {
     context.writeDockerResources();
   }
 
+  @Test(expected = IllegalStateException.class)
```
Comment (meltsufin) [inline java-runtime-builder-app/src/test/java/com/google/cloud/runtimes/builder/config/domain/BuildContextTest.java]: Can we test the actual exception message as well for both location?

File: java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java [hunk 9]
```diff
@@ -49,6 +51,8 @@
 public class BuildContext {
 
   private static final String DOCKERFILE_NAME = "Dockerfile";
+  private static final List<String> EXISITING_DOCKER_DIRS =
+      ImmutableList.of("", "src/main/docker/");
```
Comment (aslo) [inline java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java]: Small thing, but I think it's cleaner/less error-prone to just declare the full dockerfile path in this list, rather than build it dynamically later. Something like
```java
  private static final List<String> EXISITING_DOCKER_DIRS = ImmutableList.of(DOCKERFILE_NAME, "src/main/docker/" + DOCKERFILE_NAME);
```

File: java-runtime-builder-app/src/test/java/com/google/cloud/runtimes/builder/config/domain/BuildContextTest.java [hunk 10]
```diff
@@ -87,14 +89,36 @@ public void testWriteDockerFilesWithExistingDockerignoreTerminalNewline() throws
...
+        new String[]{"Dockerfile",
+            "Custom Dockerfiles aren't supported. If you wish to use a custom Dockerfile, consider "
+                + "using runtime: custom. Otherwise, remove the Dockerfile from the root "
+                + "to continue."},
+        new String[]{"src/main/docker/Dockerfile",
+            "Custom Dockerfiles aren't supported. If you wish to use a custom Dockerfile, consider "
+                + "using runtime: custom. Otherwise, remove the Dockerfile at "
+                + "src/main/docker/Dockerfile to continue."});
+
+    int errorMessagesMatched = 0;
```
Comment (meltsufin) [inline java-runtime-builder-app/src/test/java/com/google/cloud/runtimes/builder/config/domain/BuildContextTest.java]: I would prefer two separate test methods, although you can create a utility method to reuse code.
Otherwise, it's not clear which of the two tests fails because all you'll see is that number of expected errors not matched.

File: java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java [hunk 11]
```diff
@@ -49,6 +51,8 @@
 public class BuildContext {
 
   private static final String DOCKERFILE_NAME = "Dockerfile";
+  private static final List<String> EXISITING_DOCKER_DIRS =
```
Comment (meltsufin) [inline java-runtime-builder-app/src/main/java/com/google/cloud/runtimes/builder/config/domain/BuildContext.java]: nit: `EXISTING_DOCKER_PATHS`

File: java-runtime-builder-app/src/test/java/com/google/cloud/runtimes/builder/config/domain/BuildContextTest.java [hunk 12]
```diff
@@ -87,14 +88,42 @@ public void testWriteDockerFilesWithExistingDockerignoreTerminalNewline() throws
     assertEquals(expectedDockerIgnore, readFile(getDockerIgnore()));
   }
 
-  @Test(expected = IllegalStateException.class)
-  public void testWriteDockerFilesWithExistingDockerfile() throws IOException {
+  @Test
+  public void testWriteDockerFilesWithExistingDockerfileAtRoot() throws IOException {
```
Comment (meltsufin) [inline java-runtime-builder-app/src/test/java/com/google/cloud/runtimes/builder/config/domain/BuildContextTest.java]: One final thing...
The two tests look very similar. I think an improvement would be to create a parameterized test method `testExistingDockerfile(String dockerPath, String expectedErrorMessage)` and then just have a one-liner in each of tests below calling the utility method. WDYT?
